### PR TITLE
Changes to air polution request from OWM with OWMs auto time and time zone

### PR DESCRIPTION
**Pull request by sudoMakeThisSecure**

### CODE REVIEW

**Comment by sudoMakeThisSecure** [comment]
Sorry, I'm new to git still. I didn't realize that the changes that I did to my fork AFTER the pull request, would be added to it.

They are the updated dependencies, for the POP fix. And battery cal and voltage changes.

Originally, the code would stay running till the battery voltage reached 3V which would absolutely do a lot of damage to a Li-Po battery. 
You should NEVER take a Li-Po battery below 3.5V as it will DRASTICALLY reduce its life span
https://oscarliang.com/wp-content/uploads/2017/02/Lipo-battery-guide-Voltage-vs-capacity-used-percentage.jpg

**Comment by pivoine31** [comment]
Thanks for all that stuff.
I'm not a github expert neither, but I will try to integrate as soon as I'll find time for.

**Comment by pivoine31** [comment]
Did you report this battery information to L Marzen, since he is the software developper ?

**Review by pivoine31 — APPROVED** [review]

**Review by pivoine31 — APPROVED** [review]

**Review by pivoine31 — APPROVED** [review]

**Review by pivoine31 — APPROVED** [review]

**Review by pivoine31 — APPROVED** [review]

**Comment by pivoine31** [comment]
merge aqi auto TZ and battery threshold fixes from Asdf1qaz

**Comment by pivoine31** [comment]
I have merged your commits into my main branch.
Concerning the battery voltage multiplier, I will move it as a customizable define in config.h for commodity.
Thanks for your contribution.


-------- Message d'origine --------
De : Asdf1qaz ***@***.***>
Date : 30/08/2024 02:33 (GMT+01:00)
À : pivoine31/esp32-weather-epd-pvmod ***@***.***>
Cc : Subscribed ***@***.***>
Objet : Re: [pivoine31/esp32-weather-epd-pvmod] Changes to air polution request from OWM with OWMs auto time and time zone (PR #4)


Sorry, I'm new to git still. I didn't realize that the changes that I did to my fork AFTER the pull request, would be added to it.

They are the updated dependencies, for the POP fix. And battery cal and voltage changes.

Originally, the code would stay running till the battery voltage reached 3V which would absolutely do a lot of damage to a Li-Po battery.
You should NEVER take a Li-Po battery below 3.5V as it will DRASTICALLY reduce its life span
https://oscarliang.com/wp-content/uploads/2017/02/Lipo-battery-guide-Voltage-vs-capacity-used-percentage.jpg

**Pull request merged**
